  global:
    scrape_interval:     15s # By default, scrape targets every 15 seconds.

  scrape_configs:
    - job_name: 'pdu_data'
      static_configs:
        - targets: ['host.docker.internal:8000']